---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: letsencrypt-staging
spec:
  template:
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-staging
    spec:
      acme:
        email:
          getValueFrom:
            kind: Secret
            name: clusterissuers-mail
            namespace: cert-manager
            path: "{.data.email}"
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-staging
        solvers:
          - http01:
              ingress:
                class: traefik

---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: letsencrypt-production
spec:
  template:
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-production
    spec:
      acme:
        email:
          getValueFrom:
            kind: Secret
            name: clusterissuers-mail
            namespace: cert-manager
            path: "{.data.email}"
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-production
        solvers:
          - http01:
              ingress:
                class: traefik
