---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-wildcard-lan.yaml
  - certificate-wildcard.yaml
  - middleware-basicauth-dashboard.yaml
  - sopssecret-traefik-dashboard-auth.yaml
  - tlsstore-default.yaml
