---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8up
spec:
  interval: 1h
  chart:
    spec:
      chart: k8up
      version: <4.5.0
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: flux-system
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
