---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

# Don't use the Helm chart for now, as it seems to be abandoned
resources:
  - https://kube-vip.io/manifests/rbac.yaml
  - daemonset.yaml
