---
extends: default
rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start:
    present: true
    level: error
  line-length: disable
  truthy:
    level: error
