---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/cert-manager
  prune: true
  timeout: 2m30s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-composable-operator
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/overlays/wieseschwarm/cert-manager-resources
  prune: true
  timeout: 2m30s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cloudflared
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/overlays/wieseschwarm/cloudflared
  prune: true
  timeout: 2m30s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-composable-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/composable-operator
  prune: true
  timeout: 2m30s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-db-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-mysql
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/db-operator
  prune: true
  timeout: 2m30s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-db-operator-dbinstance
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-db-operator
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/db-operator-dbinstance
  prune: true
  timeout: 2m30s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-grafana-k8s-monitoring
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/overlays/wieseschwarm/grafana-k8s-monitoring
  prune: true
  timeout: 2m30s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-grafana-k8s-monitoring-crds
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/grafana-k8s-monitoring-crds
  prune: true
  timeout: 2m30s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-ingress-nginx
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/ingress-nginx
  prune: true
  timeout: 2m30s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-k8up
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/overlays/wieseschwarm/k8up
  prune: true
  timeout: 2m30s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-kube-vip
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/overlays/wieseschwarm/kube-vip
  prune: true
  timeout: 2m30s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-metrics-server
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/metrics-server
  prune: true
  timeout: 2m30s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-mysql-operator
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/mysql-operator
  prune: true
  timeout: 2m30s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-mysql
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-mysql-operator
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/mysql
  prune: true
  timeout: 2m30s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-openebs-jiva
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/base/openebs-jiva
  prune: true
  timeout: 2m30s
  wait: true
