---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - flux/sealedsecret.yaml

patches:
  # Patch `.spec.acme.email` field
  - path: cert-manager/secret/clusterissuers-patch.yaml
