---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - flux/sealedsecret.yaml

patches:
  # Patch `.spec.acme.email` field in all ClusterIssuers
  - path: cert-manager/secret/clusterissuer-patch.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: ClusterIssuer
