---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "1.20.x"
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true
        extraArgs:
          # DNS-01 propagation checks must query a resolver that sees public
          # DNS, not CoreDNS. As outgoing DNS queries are blocked, explicitly
          # configure the router IP of the server VLAN
          - --dns01-recursive-nameservers=192.168.10.1:53
          - --dns01-recursive-nameservers-only
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
