---
creation_rules:
  - path_regex: .*values.yaml$
    age: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
