---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: kube-vip
          envFrom:
            - secretRef:
                name: kube-vip-env-vars
