---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheusrule-cluster-apps.yaml
  - prometheusrule-cluster-metrics-pipeline.yaml
  - prometheusrule-cluster-node-exporter.yaml
  - prometheusrule-cluster-nodes.yaml
  - prometheusrule-cluster-pods.yaml
  - prometheusrule-k8up.yaml
  - prometheusrule-series-budget.yaml
