---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://db-operator.github.io/charts
    chart: db-operator
    targetRevision: "3.8.x"
    helm:
      releaseName: db-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: db-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
