---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://k8up-io.github.io/k8up
    chart: k8up
    targetRevision: "4.9.x"
    helm:
      releaseName: k8up
      values: |
        k8up:
          timezone: "Europe/Berlin"
  destination:
    server: https://kubernetes.default.svc
    namespace: k8up
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
