---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: sopssecret-grafana-cloud
  namespace: monitoring
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:UTM2m1PXLElH/Jb4+MoMdcfGU/MjLPXqVA==,iv:tr/Q7jDOeYQs01vJNPngKR+1j4AsF8QWHUsjO8SFAsI=,tag:RoeaRlGpx8q7e3w7pat/3Q==,type:str]
      stringData:
        password: ENC[AES256_GCM,data:DrXZSNc9HnXarNreHayX+CEOZk7Ifo9whgg1baPsRGahEzHi/GsANlzsDbQoFqs97KVs+dfFLEfDY5DuPDroWjC10I6ro9Nlw55TCh53pIsbsJVqNQIE1NomEoTw3Yi2GzWWRxal5z1FgMly/ubo/P4NsnlTsjpcKOe6kv/Ge7j4cY8bZf2g+owgtEkIsHUzZX5h5mZSUO7RbmsRBoq/Vhw/tsQ=,iv:6Su/01L9C0reRTYqvpUO7Lzdy6iaVj5Zjz3CFfUFr5Y=,tag:aALlJoqw2qvF6g3GWfl8yA==,type:str]
        username-loki: ENC[AES256_GCM,data:rOFbyeMqqQ==,iv:oStX+qws2V5XiFRBNzYz3u6gGjgp4zHRQiAnOQSyNt4=,tag:mNE00eamtg/xXnUyhZVXmQ==,type:str]
        username-prometheus: ENC[AES256_GCM,data:0vkEZPivvQ==,iv:ohnrm2qtDhsRaa/VRKdO1gk/RRRZcVXjjKH6ea+wKAs=,tag:kDHTLVYNW+NEg6E1N9JMMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd3E5Y1J3c1VUeWJIb2pj
        djF6TXA2MzdIUHZ3WGJDS2NvTXh3S3dWYVE4CkhLZDZsOFFDMWtheEsxQjRqTzNI
        d3prSjV5blNVV3dpcWMrRmJGNGJZRmMKLS0tIHVCMEE5RWNrMC9DbkxuRUNJMzM4
        TmxpZGVBY1VrV21KSjBkcUZaVzFoVGsKRGW6mp5bzX/Lj3/NDclLyf7lbJDSwLv0
        gikj3V0EIrL6Y9noHAL+2e3P5XIYkLHYDJwvW9rTQuNYIeRZ/w23Dg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-06-09T09:38:50Z"
  mac: ENC[AES256_GCM,data:mQL0Ih1tYeOwkPtJLpuP2xUEk6YLvqqS4Owg/489PHgYbjtB85Gr09LQKUSrVsqvccO9pVPYpQM+0K3x2Y4T/PnH5FM1qqtVi3OBafduGmlJnZVRyDYtAZ0XpCm4ECQVk2NIQZuAYfpSi5z9jQbHUHN8a6nIuaYIQd2HB+gc/GE=,iv:WFp6R9x0hS8Qg2iOL9bDu7S1JGjJG2o6W08R7yT1/1w=,tag:4nQh1UV0AKYnVldLKfS/ow==,type:str]
  version: 3.13.1
