---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: sopssecret-grafana-cloud
  namespace: monitoring
spec:
  secretTemplates:
    - name: grafana-cloud-credentials
      stringData:
        password: ENC[AES256_GCM,data:pr/B9pCAGoNLLzElfSplvowUGVDXRclIxuIdqfHNPAS1L4JvjM4ymJ5kxrzGRwRAAuwrFRuSvXv9nabnKnBR4/uCPNxjcARakcBtykKUtZ34PTO4/NFZL+IQ5kRwWIiamKp7tt0csPBLoFsay+llfP0kR7zPHxHzbQ5Y5nyxifC+As/Z9jm0/+Uyp7qjwcundhqxYkaLKZ3oFKiZ5Cxj1nqeEIg=,iv:FdQDVPePt1yiFEHR9ULHKyLc4bIFGfcU44HLYPdkoIg=,tag:jlJ3oBWk9fK1rkpu8xXeqg==,type:str]
        username-loki: ENC[AES256_GCM,data:bccNDf/Feg==,iv:6MR06iu7vD4CDBdercDj1+ZR5sKpGZiUsBT7BMBuRKw=,tag:aHwy+4onHqZPSZP0dDAq0Q==,type:str]
        username-prometheus: ENC[AES256_GCM,data:Pzt443bXsw==,iv:6bp7pQ8dzPpV9iqkbTvD0Vj5SC96Xh0Xg0RNvjSCI/U=,tag:YmtgKNy/JhfguFYNjKo3aA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bkpsSjdEWkxOQnNDUFBo
        c1FVL0FZR3BHTXhEMXhibXpUbFJvQ0J0Ynl3CmhYSG5zTXJMd0Q0eDBqUFhWZnpK
        NEVvSWo3cE4zM2ZqR2xUZjMwR2RzWWsKLS0tIFF6Wk4wTElWbkUzckZmQTdSZFBN
        VGhpZG9oWk9CTlVlMzExOFRkUjlVOVkKqMQqFJOz/m0lLp5ueLKu3GRQx8wt69nj
        +5tVESRCzqL6iRg5Ewt6gE6/D4kS2ZupjGmOVOreF74QFyulEApBjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T19:06:02Z"
  mac: ENC[AES256_GCM,data:8WPUxQKCCrXq1v9UdzGhbsXFoV3LyLJWqtYHp6hoBmDnpQSbVuSylTuKjE0HHE9KakwN8i4kEFUHJjHVKuJ4I4sXrQprcM9uryKKkwFk2IrZ66Px7zE7JctK79mF6TAXU299amYxTQhqy8VaVLD0yoCcV9UVOOLsghjVjl1VOG8=,iv:XRRcGk/T5LJ9fkZRgIupvkLdIhImho/FtKfV2N7LYV8=,tag:jBHFGjSJP4R4yYaGnp26Sw==,type:str]
  version: 3.13.1
