---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:m3adow/wieseschwarm.git
    targetRevision: feature/2026-rework
    path: kubernetes/01_infrastructure/mariadb-operator/config
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
