---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mariadb

resources:
  - backup-mariadb-nightly.yaml
  - mariadb-mariadb-cluster.yaml
  - maxscale-mariadb-cluster-maxscale.yaml
  - sopssecret-mariadb-backup-b2.yaml
  - sopssecret-mariadb-credentials.yaml
