---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mariadb-credentials
  namespace: mariadb
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:+74EKYp+Mpc/unahzDCZYaOGuw==,iv:GgTUlBLz+hagn27PYvHa0elxFp5mONDpf18s2UcaKXU=,tag:Ngi2vEj/rKR1ykYUaQDgzw==,type:str]
      stringData:
        rootPassword: ENC[AES256_GCM,data:6v8KbHoIx5iUQAr9NXMqtEdz7gH64qmB7JYzezYEcYw=,iv:Uziw+tE51tO8aKLKOBEc2O9/l6WG+XcpfTJfdC8VyQ0=,tag:coT3/zqy/W4kqDcG2m0Hdg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eDBPc0crVnFET1d1Y1hz
        T0k2UW9aa2lXQ21EUEwvRzZMa1gzZWNkNEEwCnB2QVpmV1Z0bHppN0FLYnExNHA0
        bUZOejNjRk9SQ1lzNzRuR2NadjE4ODQKLS0tIEs3M3Q2eWd3czkzd2dkRVRhbmd0
        eDZiQnNKLzVzN3ZFdG95M1dwOTdsVmMKfBaK2Oo/JtOysxIMtGaqU38/ENVd6aPi
        B/ummTDeks3Oic2kj+694xJjpzWyQDeiUG+LZ1E+V0KxnTUXkHR7XQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-06-01T19:01:11Z"
  mac: ENC[AES256_GCM,data:t/Bc+R+NDgq3ZcQIGqGI44Gj+EXPgwSg7CBwkPJAM9jDKoqI39zfDa1Cf0Gp2MztHggOLtliJFGJfiPSjd60Bd3GtgZsAo1FxNkvCgbqXUktiNzDf5LEr6Rl8Dw90M/Vb4R1hFeCGvM20Vrhkcag7BnJfFdrJ+HE2cUNpeb2eo4=,iv:n7ML7Z6KapLC8KVutBskO4yYKqCNO+y/n1iOA8kJgHg=,tag:wCAuLvB2rbqe8VwV3WL6Uw==,type:str]
  version: 3.13.1
