---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mariadb-credentials
  namespace: mariadb
spec:
  secretTemplates:
    - name: mariadb-credentials
      stringData:
        rootPassword: ENC[AES256_GCM,data:Q3IdxgVMeUCdvjJjUpWlxJh0vd0Oqz0bHK8sKdPN1rQ=,iv:xvPX9ukvd0fjAtOJCoRukWc6J2Ih1ND9UwDZGejSmQ4=,tag:6UtiEP3ol3uBVU4sycwgiw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNUJ4M1p3RUU2OXNEQy9r
        SmM3a0JQc296RmE2Tlp4OXVQYVYzYkQralI0Cmo2dHBqdXpEekpMUDVXZUxTeDNZ
        ajZuOTFlYXhzY01wS2xRUHovdkdQVG8KLS0tIHpHdTNhejlCdXRrbFBEZE5FL3BG
        QzlIVm1Rb01ncXVkc0xIL1lXamJwSFUKbgdGtUMbYSpns/JNRngYTs1Bp9TKczt5
        oK1URnoXVW73JKW+dViMCOVjFPw+06LoC9bmBVx6BYQ5hRNw/uDgBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T19:06:03Z"
  mac: ENC[AES256_GCM,data:zDjfxQPSuyxnfd6Z7SEJlK7y3awRtd2UimjmQWUPFJgsC+ykxv3xSu3M8Z9tURnx05k/eg7X+yVvfKfejAhjksG+j5Sw14fzBefXFsOH+pJvS3tpT3vf+Qsf2hAh8pw4o4dYYplNxBMw/Q6yXN0aAef15wzOyU/Iqq7xOYJxjZs=,iv:AoVLe/i3cFqBlO44D/0yzE9XJXwURcug6nHU8wo9NRk=,tag:wtUZcUZ8ZH5NdnFy+8KCeQ==,type:str]
  version: 3.13.1
