---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mariadb-backup-b2
  namespace: mariadb
spec:
  secretTemplates:
    - name: mariadb-backup-b2
      stringData:
        access-key-id: ENC[AES256_GCM,data:xqb60d6Wn/W3KDFxtUZIV3u97xU7TafAlA==,iv:WQk8Vc9DX/hThOxq+g4meOs2zAVia0J2q89YSyS77Fw=,tag:Kxv4zKby5cQy73wPVNs7jg==,type:str]
        secret-access-key: ENC[AES256_GCM,data:dAd4/EdRuJBCg+rtAF5bKFGvbHJYA6u8dgYNUwJK4A==,iv:2sGzHY1D4EiIov861xnnizJHox6/OUN+wr+jwOk0+gg=,tag:xT8J4svSdhTHz+d4122t1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRjdsQm0zYmJXRG9UUzFq
        VGFvTVVMR2puMGRYOWNyQzZMUGpxMHB0ekJBClVZM0ljbWlSbDhpWWpuSDdLa0JQ
        RlhCa0xRTWt0cUlyZElTNmhKaWp2dU0KLS0tIDJyTzlCcW9WQXE2R3FqSTZuWkZU
        amxOaVQ5OW9USm5yMzJZMDhaQURxT0EKKoQPykC5PiboxcuVcDScLdYavt5OGm+T
        YHfqZdZUTkcbBWQpwjMltM938MLrs5vT7L6kEA3TAU697/AK2gSGPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T19:06:02Z"
  mac: ENC[AES256_GCM,data:U7q4Vy+vQk5wqsjyQ8+BRoIyU+A4Z1tJPJXx0nuTkksSIEhBRtlOf5UuhufNXlcVv3n3H6o1/LzqunijpHyiMeQYfCTsBTShf7LovTNdOO38i37mf03C/UqPcNzvvcppbnp+xolH5ljBH4YU1XnodC+S7FA0Z2bZ1u+WCgNGHoQ=,iv:w0hcoMVmrqR7jCQJThLn0UmoJ1zecL0MBYVYmi6BEg8=,tag:A6mXR5l1/ik/UTy5BZlhGw==,type:str]
  version: 3.13.1
