---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mariadb-backup-b2
  namespace: mariadb
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:hT6PiycZrf0izF0wYFEtFks=,iv:w4rAaLYOuI9wWiD8tUyCCJaU7/Egk4f8NCLAPCdVZao=,tag:Jh8wN+8tqnD/iYDl4pDbzw==,type:str]
      stringData:
        access-key-id: ENC[AES256_GCM,data:mboeM4UkYvbf3aTkx5ijyAom+TiPuhbwvA==,iv:7CDNjhus9P0Vnmw/vMoe5jfsCfITlRyVunMxq1wk0So=,tag:a4iWhWQlGlPUDDLr1/5pOg==,type:str]
        secret-access-key: ENC[AES256_GCM,data:pu7qJ3y597w8I55m/OV7Qe+k8P5Twrc+FswNSDXG8A==,iv:rwQkGSqinE6FHtJ9wJFB+kahd3dB1/T1+w3gpHyzPzo=,tag:/tQmvXR6LNSF9s1lxaz6bg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Mjl6QVpmdXNRM1RjQ2Vn
        VEsyNVlOekJJUTl5ZVpJVmxiRGN4ZFVyZnlBCm5kOUNFMkkyRkFabzVtM3dXNjhF
        M28zYTNzM1VoR0VpTW5TRnlTZ3AzVHMKLS0tIGFwdm5jcnlXL2NKK0lUV0VqZGZp
        RUx6c25DQ0l4WHhNOFQ3cnN2RHRMNUEKQGS+Ff2VfUcgT1zoG4I5LKMjR06XkUG0
        VJTvj5QUHmFMaZD9iKXcUcJxRjz9XqCc4DmFVpBBBLxK6lapz/KsTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-06-01T19:00:59Z"
  mac: ENC[AES256_GCM,data:Cv6Uf0Pg9nSdv/+rR3BExxZEQ5Fw0tqjhCRTAMjPv3IJqZKzFXrB7Q33hK+cMhxCqbAClRdBxrjcqybcv89vgjRnuS4kBapjs+aCuI99RkYnIy/jbaYFfRj0faTd7POC4UWThuV0t3KsQL6XBQz8ieGww4Xq1uQXWWr0pChqxCQ=,iv:NNzhek24Mou/tr+GM1e6qqdbvGqbszH3e9PHDhjxBDE=,tag:UyN/uH2cI8G15LuHOFmn7Q==,type:str]
  version: 3.13.1
