---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-monitoring

resources:
  - ../../../base/grafana-k8s-monitoring

patches:
  - path: helmrelease-patch.yaml

secretGenerator:
  - name: k8s-monitoring-helm-values
    files:
      - values.yaml=files/values-encrypted.yaml
configurations:
  - kustomizeconfig.yaml
