---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://mysql.github.io/mysql-operator/
    chart: mysql-operator
    targetRevision: "2.2.x"
    helm:
      releaseName: mysql-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-operator
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: innodbclusters.mysql.oracle.com
      # A slight misconfiguration in the CRD's schema causes a perma diff
      jqPathExpressions:
        - .spec.versions[].schema.openAPIV3Schema.properties.spec.properties.keyring.properties.oci.properties.endpoints.description
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
