---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mysql-credentials
  namespace: mysql
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:nRFzBvLjyOrin9KOUlz3MQI=,iv:KjBYoXU9InGTFV6NoIvvmEs/n3D7P3aC7hi4ta7UnZI=,tag:1igdb1iyTr2eWt0LY7CwFg==,type:str]
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:7kEyeQ==,iv:obDDyhJRC+L3sAKV+A+DIND3lSJCu96zlRlvYFvnATQ=,tag:0iyEn8A9kkDB03ZC1/1lZg==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ENC[AES256_GCM,data:VKBs03/h1Q6KbNE=,iv:hnfA0UsS5dSSwytSl7YYxunFUXw9FmXL5ujM0bg5cQ8=,tag:V7HZYx8VWHPFymzGdJeONQ==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:MByy3g==,iv:miEcALzFvp1houjIH9EVT6JpmeWHUesGGP+zcNsZng4=,tag:43LstYdSH0ing2Wd2CUuZw==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:K4I+0MjkEAlTuZg=,iv:h/XQqYSQQKyp1QPh7rel0WvrGLvjmNkGnHDIGZ563mk=,tag:ZTX5iAk9psu4uhKBi3vcnA==,type:str]
      stringData:
        rootUser: ENC[AES256_GCM,data:eUd4Cw==,iv:1opu/+ZaMHfWLIU1vuVeVteCpQeSZN67aeQ8zpcSy9I=,tag:IQUuyf9iE5SEdvRTMeumZA==,type:str]
        rootHost: ENC[AES256_GCM,data:lg==,iv:DyKAr2xGpieeO5Y3TXxwYLPm8b9JpokTZIlD2lY0o+k=,tag:P8/M0JCrABYI33osPI0/XQ==,type:str]
        rootPassword: ENC[AES256_GCM,data:h+x2pOmH/nHCNN81s1Jy34amISYOv29WpWVHYvcX9g==,iv:+/ChgNBFfz9Sj01h0YEXvSn0z9g4SGsiDf6Md/sb3PE=,tag:nOxXNw4ASndwIlr9oMwhew==,type:str]
        user: ENC[AES256_GCM,data:YuadyQ==,iv:89HZdOz4V+ag4PsLLGWDfp9UsRa6MUP9nOYx0hKelIQ=,tag:zDSi81jGzutwAr1Qj4KAJA==,type:str]
        password: ENC[AES256_GCM,data:kHmwaVM6NqJvoEUdrHOQxv1E+EJLuXRgPRTSMPoeZQ==,iv:El5YgsQwBqxDJnlid2MRPAnpBlR+iVayz30RinGn9aw=,tag:PV6jR9cpeaXytR8Yt3WqFA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSzRRSDVza0tpSjlqT09y
        dzY2N0ZpL3U4eTdhci9DVWd0UWZPNUdSZW1vClJOUlN3R3RZVXNtZjlRTEdmODRR
        Q1ZncFZPdHJ4VHRCRUxMdjFFdHpvcm8KLS0tIGZ5MDNQcWdjaXVIUVBwNjVDdHBv
        TEpmS1A3dU9IYTkwVWlLLzZ2Yk1sdUUKmo6j9f7TPgv6Cs9eHmvcZEBV+hD3A1vU
        XytGvOVivEiyo15v8U7oj+dkMU0+SFTxlUPgxaqnzqPcW3Gm8gIBJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-06-01T14:44:11Z"
  mac: ENC[AES256_GCM,data:B+1XjMFymatESSvGeJOflkfoXVVhF4EG9ZYrso5rSA7CauZYtlFk8PgwLrtmlo3acHU6XJqyeY3LpwBNXR0GnlBHTssBq1C1pkYK9znNuK20xEiWsNyn49Ma8+JlaKCFQEaU6AMxUdrAc4loiGfmDXzdb+kqZatsc4zieSB+9EM=,iv:ZtS1kseiK3uC3EGoXLnMX7kgMquGe2abGNd5FEV+KQQ=,tag:P8uyCp53DOj1Isasriypfw==,type:str]
  version: 3.13.1
