---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: mysql-backup-b2
  namespace: mysql
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:yLVE4N35ye0f/H7dF7Mr,iv:tYWVWlvNgQCOFf4gUJ4/uam6TOG6+NRrQmc5WycGr6U=,tag:1EOrAEEN6oJUvs+MJDtseQ==,type:str]
      stringData:
        credentials: ENC[AES256_GCM,data:hMAqQjlgi70STfQZSpapHUT3xc5ADIoG8H+OdiJryVRsXMamU3Ql4cZmxMWi+7nt2VxTX85s1AvLDyGNxo+sMgRO7PivCk8slZXXrRreowxYU2LfBk3l9Sj2ACSw+a/qxntIr//6xuMACBB7,iv:p1kEN6XJkaxWIWMOBMemD0FnrUnqzvmlZfj8vkspmHc=,tag:IvMPNru0qhL9cocZqzZ1vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZW9hVG1mVy9uYWRMRHB1
        ejAzOVRzVTZZWkt0NjBvMTNlcksvK3RyZFFrCmR6V0FGYlRXdDNDam9UWXQvb08x
        UEpQdGlZN0dmS05MeERDdktoSnp6MEEKLS0tIGJvVTA4bUxaSXZzOE1mdWd6eVZp
        VUljRjhnb0Z5cGNEczFVN01BWjBBTzgKSjdP53CjEH/hQKJnA+upHbJ7UFpl8ZyA
        T6XGYpUi+8nB/LFmwfMG32EinWuHZzey6IMPxkvhrgG2f0gpP55jcg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-06-01T14:44:11Z"
  mac: ENC[AES256_GCM,data:iorI660HWJ63NOTcw0euOff414C9Ks7dTgxfllBFAWIWWZTFak3ikA2NZwPVyXyFfxGZKMHudBg6ZSIloO3nf22BnnGukLiftO1JnWVBShCjicgwBsIIhSy4PHXUnZ+6Bt2kdtRh182Q61eEGojUPuMhP6Cl3LlUrXIgJrwEHhw=,iv:KHHOBp795WcZj+BCdKiO4pDlu/VcssqWZ4vSrCID6Do=,tag:C9cXPtjW69DSzHm50LJjPA==,type:str]
  version: 3.13.1
