---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay includes gitignored secrets which are initially applied to the cluster to bootstrap resources
# e.g. SOPS keys for Flux.
resources:
  - ../wieseschwarm

  # Flux Repo Identity for Wieseschwarm Repo
  - secret/flux/secret.yaml
  # SOPS keys
  - secret/sops/secret.yaml
  # - secret/grafana-agent/secret-basic-auth-passwords.yaml
