---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay includes gitignored secrets which are initially applied to the cluster to bootstrap resources
# e.g. Sealed Secret keys or Git credentials for Flux.
# As the Secrets should still be managed by Sealed Secrets afterwards, the annotation 'sealedsecrets.bitnami.com/managed: "true"'
# is required.
resources:
  - ../wieseschwarm
  - namespace.yaml
  # Sealed Secrets keys used for encrypting the secrets in this repo
  - secret/sealed-secrets/secret-sealedsecrets-key.yaml
  # - secret/grafana-agent/secret-basic-auth-passwords.yaml

patches:
  # Flux Repo Identity for Wieseschwarm Repo
  - path: secret/flux/secret-patch.yaml
