---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/02_applications/base
  prune: true
  timeout: 2m30s
  wait: true
