---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: init
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/01_infrastructure/overlays/wieseschwarm
  prune: true
  timeout: 2m30s
  wait: true
