---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: init
  namespace: flux-system
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
  path: ./kubernetes/00_init/overlays/wieseschwarm
  prune: true
  timeout: 2m30s
  wait: true
