---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main-db-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: openebs-jiva-csi-default
