---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sopssecret-cloudflare-token.yaml
  - sopssecret-dns-resolver.yaml
  - clusterissuer-selfsigned.yaml
  - clusterissuer-staging.yaml
  - clusterissuer-production.yaml
