---
# Cloudflare API token permissions required:
#   Zone: Zone: Read  — All zones (cert-manager must list zones to find the right one)
#   Zone: DNS: Edit   — wieseclan.eu.org (or All zones)
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cloudflare-api-token-sops
  namespace: cert-manager
spec:
  secretTemplates:
    - name: cloudflare-api-token
      stringData:
        api-token: ENC[AES256_GCM,data:YepKJdSpdaiHqIigIznzZniVt1imr4+UWgUaBrbgyJAw6ibFT4WVlg+FLz95VBeKIPnllik=,iv:VO6dBY7MSEXE5pXvZkBswaIljxfU12JkrRMi84baA/Q=,tag:CkvYbYEHXUUyOIPZ9Ylwbg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaEMyUExxdkFUK1VsMG1a
        bjVxRjJvMGphYUFpa1JmcnhQalFieDh3TlhBClhrMjkxbVUwS1ZaZitFTnJTVnRM
        L25wS24rYXpiMFVKTDBUMk5VczRZV1EKLS0tIElkMDBFeW00NkxUdStzSFNZL2FZ
        TDFJWE9IYjF1c2VTM0h0cGx4eDMvVWcK7mmoQIwSDIBod5w3UC5xLbJrkOVF90wC
        bx3Xk276ddoMDPUMnRkkE4Gz1ygOPzDRa89kMLTpxBLvSVlrS3UxmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T19:06:02Z"
  mac: ENC[AES256_GCM,data:HyTA9UnllRkxPTupqGjbFju/q1rO6YmYMU7Rn0usLgPy/s5GoCeNjl4ojKQdWmIRtC3mLeC4DB8g68Hnb+/rrQezOCl66n4Qun6yxstWup+elnDf3RBLfTlGLrIpFblFSeYf8Y6KRMJqNpCVTIzaUt2UBlgr6rxUGfyWmZlgPX4=,iv:neCLCFRX8YvXw84f/QkDZc6TnVJBp1pecPOr84RboUo=,tag:KiYTiHqL5k6h2U9cWDATbA==,type:str]
  version: 3.13.1
