---
# Cloudflare API token permissions required:
#   Zone: Zone: Read  — All zones (cert-manager must list zones to find the right one)
#   Zone: DNS: Edit   — wieseclan.eu.org (or All zones)
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cloudflare-api-token-sops
  namespace: cert-manager
spec:
  secretTemplates:
    - name: cloudflare-api-token
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: external-dns
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: external-dns
      stringData:
        api-token: ENC[AES256_GCM,data:YepKJdSpdaiHqIigIznzZniVt1imr4+UWgUaBrbgyJAw6ibFT4WVlg+FLz95VBeKIPnllik=,iv:VO6dBY7MSEXE5pXvZkBswaIljxfU12JkrRMi84baA/Q=,tag:CkvYbYEHXUUyOIPZ9Ylwbg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaEMyUExxdkFUK1VsMG1a
        bjVxRjJvMGphYUFpa1JmcnhQalFieDh3TlhBClhrMjkxbVUwS1ZaZitFTnJTVnRM
        L25wS24rYXpiMFVKTDBUMk5VczRZV1EKLS0tIElkMDBFeW00NkxUdStzSFNZL2FZ
        TDFJWE9IYjF1c2VTM0h0cGx4eDMvVWcK7mmoQIwSDIBod5w3UC5xLbJrkOVF90wC
        bx3Xk276ddoMDPUMnRkkE4Gz1ygOPzDRa89kMLTpxBLvSVlrS3UxmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-10T08:53:01Z"
  mac: ENC[AES256_GCM,data:/wC/aXANaCjOF/CD58LeayzB+ssQiyu1v4Nb8u7XfVbkVgCHjif8POQZcpOcL2bXxwGnWkES1beVUUDN7mpr8y1TewEUhwHKlfLrA4abUSaRyq8O7EnJNbZ23Fc37dDB2QU2Ll9mYxc1ZQ9RHkM9SplNQJqTtRpCRWq5Q0dO254=,iv:fqVGK9wOGbJVKkslcczuIMvEspQKRMn2TIk1n9IButU=,tag:1WgiScv9NKJka+Un3sFLIg==,type:str]
  version: 3.13.1
