---
# DNS resolver used for cert-manager DNS-01 propagation checks.
# Must be a recursive resolver reachable from the cluster.
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cert-manager-dns-resolver-sops
  namespace: cert-manager
spec:
  secretTemplates:
    - name: cert-manager-dns-resolver
      stringData:
        recursive-nameservers: ENC[AES256_GCM,data:WHk4PYVlFM/eWjMOd1os,iv:pj5PcCmE2cXBUtvyazcdXpBmE4Yi0rB+lPRlYgm8HYo=,tag:el8idl9rrtm0BDglV8o3AA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMHJiSGhGVHJtTU5Yb0dK
        eGZpNERsNGRJQjkzcGNtc29pZ01lOFlFTlVZClQ3amdkWHc3TXdlQTRkK3V4S3lK
        Slo3UzNsZjZNbCtUbytTcit1ekp4S1UKLS0tIFFLVlFuRURJNWJaZzZqL29OWStQ
        SVhWWVY0bGUwK1lwVXNXL1NjUlJTNUUKRUMvVUXV3jFfj76fgJIdJRmvHSzPJ+j7
        Qqfxu0TESr3TP2MQXzANYAw5ggnNkBNseYJr4xwNJyrzSKXB9JxVxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T19:06:02Z"
  mac: ENC[AES256_GCM,data:U2FJZWM0EHrx3xhO0ekxsvIOrTgGuVznGsAhb5x26yVxLNEbhTGIVae+xTvpbLpg/To/Ipr5hLOXxHM/k3CmXQhHvJFKFj+HmkwkzcKEDsKQNhqzyZmVpDpJeUX4FuTVodscDJy4Bc0X6uIfMTM74w1FS3cD4o9BTJ/5cwiRp5c=,iv:rdhUsjIrqJ7nI9k3FIosUKXp8ubeQX7LGIRvdX8VSjY=,tag:SbHxWq8K/Iyw7d6KRoEZUw==,type:str]
  version: 3.13.1
