---
# Cloudflare API token permissions required:
#   Zone: Zone: Read  — All zones (cert-manager must list zones to find the right one)
#   Zone: DNS: Edit   — wieseclan.eu.org (or All zones)
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cloudflare-api-token-sops
  namespace: cert-manager
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:xNGbFbLLBBdzSWrOp1Ftf6d7vms=,iv:BJJ0HubaodGGsaOzhjarhm3bluTzhHaGC/556jNpwtI=,tag:JEos1vSJdpwtUHj39f0Mtw==,type:str]
      stringData:
        api-token: ENC[AES256_GCM,data:leqiqyhuK0IvjDKps/XB8WzBkwxvmRep8CyL+gbIKzP1+QdpoaKZhmwivd04iJwPzaNoalM=,iv:dwMMbKJg5AaDOExVpJNtMrZJWXYmUODDIGL+do31vKA=,tag:tVR+PWWa85HUClN0GXq71Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTUVvSXpsRFRGdEZvV0RC
        WlRnTER3eVFoWlFPYkhKOUEwZUdSM1RmYmxjCmZzbkhFNDgrWkk0NngzTDZIRDdi
        MzRhVXEweEdLSnBZYzFFRnJwRGM0L00KLS0tIFdqVnlmREwrVHJlVUdJT1U5RWlM
        ZEdyVWE2eGhmaWU4b1M2bnJheHd5SXMKGRVbdOP3VOtysih3e/QUAhhuSJoEc0v+
        QyU+Rl/R8bJw5T4fv/WBYv8p6WoK5DF/xzZu0FwmaJv8WspK306dKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-05-31T13:39:30Z"
  mac: ENC[AES256_GCM,data:1gcepOenOi/TZueSTkUn3cuzTscGmjZ8VjIWOTw/rB3QaTMx8bI9RXx6jn+b2lrk4OE1KP+Ny4cXQGVMtWHNtW8dyARA1WJbqoRDyicGd/D250SszXPlW0IvvJlLUMzc48gWSzsZ1NsJkJDMsVz7JKYJIqsddkaTBtVYRXVIfZ0=,iv:fi8jPxd+GvKrbxesBfAQXZtaBVfgpQ2RCQ6KL2oW5jg=,tag:6GHCP879VQ+BA1zB+ho+ZQ==,type:str]
  version: 3.13.1
