---
# DNS resolver used for cert-manager DNS-01 propagation checks.
# Must be a recursive resolver reachable from the cluster.
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cert-manager-dns-resolver-sops
  namespace: cert-manager
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:GqLMMDmNEEXXr2ygNkCRl0v+MO3qIKnnnA==,iv:gNvC6fhSpyKM89ayvJVpv4Bs1mjD+2/yqRk2iPnVh2U=,tag:hzJSwA1xP4/SDUFE8dDreQ==,type:str]
      stringData:
        recursive-nameservers: ENC[AES256_GCM,data:7qVdCtXGjRXGx1uEUVum,iv:N7Zf2FUJwrj0fIAUrPn+jWL/KjhTOa2U72kd86qlWqI=,tag:QPtG7E3/YH30t0h3PJ2yuA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU3BIemN2cVY4a1Ixak1J
        eU9LWG5qdUxHVjMxTnE5WVFzaW5wVG9qVUJ3CmRBalJQRVZyUlpsckRMSkJZM3R0
        Q0FyUXBKVFdkT0JicytWZ3dsMVJBZnMKLS0tIFRDb1hIUnBLK2FjOUNWY3Iyb0ZO
        Y05XWmpZY1hrRU1zUnNmSzlybU9oZVEKE/Mje1Y1/f/zTwcZAKzEnHBx5xkb0TeH
        0r33sDfbUbduzmm67Jnfg0Ki7V3N40BodBcVqDr3/Eg+fHoU44z3WA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-05-31T16:17:27Z"
  mac: ENC[AES256_GCM,data:Ik4zxA04UyWXYFawozWhjcnTjAI3sI42gUcQ5SYlpqhyzioo9xr+SUxxpDFAEwuPAtJQiX2ZuO3X3oEWQTAN88/uXwCS9Rzs8UNgwzLEexjqImQU0i+zY93//KXoMVSAfYlPvsnZFrRCMGr9NxzsaLyQA8WS06cq/KdLSZKSgRw=,iv:VJJ4Mb0QOeAH8hGPJwU9ceiwlpWvV1UNFA+VY1OwOBw=,tag:/tJFDKaWXALZxu4UhNCT1w==,type:str]
  version: 3.13.1
