---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - github.com/fluxcd/flux2/manifests/install?ref=v2.1.2

  # Helm repositories required for applications
  - helm-repositories/bitnami.yaml
  - helm-repositories/external-dns.yaml
  - helm-repositories/grafana.yaml
  - helm-repositories/grafana-k8s-monitoring.yaml
  - helm-repositories/jetstack.yaml
  - helm-repositories/k8up.yaml
  - helm-repositories/kloeckner.yaml
  - helm-repositories/mysql.yaml
  - helm-repositories/nextcloud.yaml
  - helm-repositories/ingress-nginx.yaml
  - helm-repositories/openebs-jiva.yaml
