---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - 00_bootstrap/argocd/application.yaml
  - 01_infrastructure/metallb/application.yaml
  - 01_infrastructure/metallb/config/application.yaml
  - 01_infrastructure/cert-manager/application.yaml
  - 01_infrastructure/cert-manager/config/application.yaml
  - 01_infrastructure/traefik/application.yaml
  - 01_infrastructure/traefik/config/application.yaml
  - 01_infrastructure/piraeus/application.yaml
  - 01_infrastructure/sops-secrets-operator/application.yaml
  - 02_applications/application.yaml
