---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: db-operator
      version: <1.8.0
      sourceRef:
        kind: HelmRepository
        name: kloeckner
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    config:
      instance:
        google: {}
        percona: {}
