---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: mysql-admin-credentials
spec:
  template:
    apiVersion: "v1"
    kind: Secret
    metadata:
      name: mysql-admin-credentials
    data:
      user:
        getValueFrom:
          kind: Secret
          name: main-cluster-credentials
          namespace: mysql
          path: "{.data.rootUser}"
      password:
        getValueFrom:
          kind: Secret
          name: main-cluster-credentials
          namespace: mysql
          path: "{.data.rootPassword}"
