---
apiVersion: v1
kind: Namespace
metadata:
  # Required for OpenEBS Jiva, see:
  # https://www.talos.dev/v1.5/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/#patching-the-namespace
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: openebs
