---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system # Namespace has to be explicitly set for Renovate
spec:
  interval: 6h
  url: https://kubernetes.github.io/ingress-nginx
