---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: k8s-monitoring
      version: <4.5.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    metrics:
      cost:
        enabled: false
    opencost:
      enabled: false
    prometheus-operator-crds:
      enabled: false
