---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: ${WIESESCHWARM__REPO_REFRESH_INTERVAL}
  path: ./kubernetes/03_clusters/wieseschwarm
  prune: true
  sourceRef:
    kind: GitRepository
    name: wieseschwarm
