---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wieseschwarm
spec:
  interval: 0m30s
  path: ./kubernetes/03_clusters/wieseschwarm
  ref:
    branch: develop-2023-10
  secretRef:
    name: wieseschwarm-repo-identity
  url: ssh://git@github.com/m3adow/wieseschwarm.git
