---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wieseschwarm
spec:
  interval: 0m30s
  ref:
    branch: main
  secretRef:
    name: wieseschwarm-repo-identity
  url: ssh://git@github.com/m3adow/wieseschwarm.git
