---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-public-tls
  namespace: demo
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: demo-public-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - demo.wieseclan.eu.org
