---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-nginx
  namespace: demo
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
      }
      server {
        listen 8080;
        location /stub_status {
          stub_status;
          allow 127.0.0.1;
          deny all;
        }
      }
    }
