---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: demo
  namespace: demo
spec:
  mariaDbRef:
    name: mariadb-cluster
    namespace: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
