---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-lan
  namespace: demo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`demo.wieseschwarm.lan`)
      kind: Rule
      services:
        - name: demo
          port: http
  tls: {}
