---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-html
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: piraeus-replicated
  resources:
    requests:
      storage: 64Mi
