---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  endpoints:
    - port: metrics
      path: /metrics
