---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: demo-k8up-b2-sops
  namespace: demo
spec:
  secretTemplates:
    - name: k8up-b2
      stringData:
        repository-password: ENC[AES256_GCM,data:aiPW51VNIqoVp0cGjRWG+1rvlI0ToDkWJ2usoN1wHJphQiDlP5W6620Kk4YxLbS8j4A=,iv:e2XS3klsgM4/zmktBrEbjQYbNcwF89LOiayL9FOVuvE=,tag:wesmnWBwGF0KVRuzesxWrg==,type:str]
        account-id: ENC[AES256_GCM,data:h54ft0KHeQMsoyml23XUNptbj/mPx78OaQ==,iv:8fsQMnV+W3/q7/2g5Gz76ZmlNXH0gE7lRx7TFBVlndw=,tag:1gXF1xxSNi1gZhpAFVTtgA==,type:str]
        account-key: ENC[AES256_GCM,data:xD3KMwvv4ieqTFRX6+5FwEmZcXx7j2yZAhnOAlLx7g==,iv:U4ZqmfooAkQKwK3qvHGqOzhgMb9+rjiXt1mMBwJ5vgU=,tag:oq0A2Bj0cxJ9QTJbBYe6Gg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ckJvV05pUzBkSzg5V3Zi
        WG8xQVNkOWVvdHRmYzhpeUVGOHZvOXdJNm1BClAycDRaR3FWdkU3WEFXMzJ3UEhH
        QTA1R2xzSEUyY2VuVUVpQk42cnhubDQKLS0tIHladDhGUTk3ZEV2UTBaaVJzbFAr
        VnVCUy9zQjkxOHR3V1licmdKLzJ3REEK3S5fH/Q2XMFT3T7K4fq4qUWkZFPziS4N
        hGss8265vlOOKgnrkT3Ku88kDuV87kjHSaVzliHPfiVz9bxkVhDOFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T19:06:03Z"
  mac: ENC[AES256_GCM,data:wi2jmvr5C2VUspkZ8DiF08oHoXVWICcDe1e6WkbKnCmB/9ZUF9VK0Mm0T7US31SLezomojH4NEp1ypplk3g0SurvjNwLt19Zm5LdqbSoDLwiBdZscEd8tG8/HG0Qwac5Jb1+1TKsNXNCPOvY05qJCihcOFiJiEUn6cKHOw9O/ZY=,iv:0igHTWQ/1vDdVx0/5bYN5+Xrs6pkIV5WP+tc16FPQDk=,tag:3HjrqAOGO7B6Nn5mYCY2FA==,type:str]
  version: 3.13.1
