---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: demo-mariadb-user-sops
  namespace: demo
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:AY+ctarEzQLzMUfipvGNjZ8=,iv:Rbwqf6ALoC09yUmR98GnCu4jEeQu8I1ADyuuCm71WlY=,tag:LBFMejZM2f3LqR6W/X9aFg==,type:str]
      labels:
        k8s.mariadb.com/watch: ENC[AES256_GCM,data:GX4EBQ==,iv:+VF0UOAqZSIOLghQOOG+BDQX21W02OUiL4qQ4WK+BwU=,tag:gnKqfq2r8mbFb6Jn8lQNYg==,type:str]
      stringData:
        password: ENC[AES256_GCM,data:5dB8SVNu+iHgOWeN3rIDcGrmlk3VwPqTDMxoCRvfQ/UYV9gpJNhi/mDDEqrISg1rBQ==,iv:qJpgHUc+Ur1STLnKmoX9AQfKS0W9qysChmJkVYe1tBs=,tag:f1ie+KLk3UxCK1MJ+9mY7Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZjZsR2ZqR1dVdzMyWUk2
        c2FpVzU1NzRZbTk2QjBFV29qaE16cC9XckdZCjFoVkwvNUtwNVd1T2lGNXNLUEFI
        QUpmYUdKaHk2STJZSCtkeUQ3M1NxdkUKLS0tIFhDWnNVWU4yUi94TFg0blB3eVpp
        RXVLYU5PdTdiM2thYXdYMmY1QnFDZWsKsMJ13uc0UA9sEFK7Pc7GFcUuCfn0V0yy
        9RmfsGaY8GqdMDjueVEhkZqY5f2nQ+NCuaAGzvNldzHwx4B1PwVd6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-06-09T18:56:12Z"
  mac: ENC[AES256_GCM,data:Ps/EMXfLzx6hK9bLt1e/bYsnAjno9/qx5V2NVvuAZBfApjOtD9dou7ulzv5gwWly6Y8rxHG0moSbZ0J9gEq+HO6FuzE8trgbwoBb0gAFaSPgVYK56KHfUN6RJeMG3zD72bHPAJ3VAQKUyFP/NXAqZbHlhO4l4/8wWu5B5FVADss=,iv:rkwOBkV2hri/hRSkY6gAFGiMNRxrAE1Hc1XnyIlGxEE=,tag:p7xsYSsSeH53n8B5yOJv1w==,type:str]
  version: 3.13.1
