---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: demo-mariadb-user-sops
  namespace: demo
spec:
  secretTemplates:
    - name: demo-mariadb-user
      labels:
        k8s.mariadb.com/watch: "true"
      stringData:
        password: ENC[AES256_GCM,data:LVPRuUKC7A+ujNpBlGTXrb1Ugy2PLe421m3fMw70rU3m2NkpJcE56RN1IuicWCcMhg==,iv:xX0lAtpPt3OPkx8DumloLkoTeCHkGLhOE940bTwnvas=,tag:HzL4XgDryUx5vKM25XEbmg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQlhFWTFNNFRzdTdmYUpr
        cVdYbW1oOUc0ZEQ0dVJraU9wUENjOC9vaUQ4CnZYYkpQa3k2bHc3eC9vcGExbkNx
        VE1sdlhPbTJTKzhUR29QMmNWeFd3d0EKLS0tIHBsV0ljOElZMWsyVDJhQ0NzRVg1
        UVRoQ1VZT0xBMitGcnpzMk5xb0c5ZUEK/u0PGxONqFD4e1K6mTbfrKn79MMmqJ8r
        G6HhMzygwcp+FYbstlLPZ684hYAlgAVBXpipxcUy7u2aP6G3UAiuDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-09T19:06:03Z"
  mac: ENC[AES256_GCM,data:FVuqrwhfX27KpJNkb3K6NEbxUSYB92mVvLHp80lUinLNz8mDJjxcGBxZGBPFmuOEpBf5v6Ebc3BTuqb0Bw2PD2G1PnR9g5BY0E8D6BPAtCfoRlTi0sI2DKbEG+17gH69zsi5A5PoTzQPYjn2qjfn7qbCIWfhxw8Z2h+dzFqFR/g=,iv:MSx4kw24lzfsi6wrmdiSGrWhvacxgEsqAzEhw3bqErw=,tag:pPJ6GEjcHVoNg6kmtzaZTg==,type:str]
  version: 3.13.1
