---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: demo-mariadb-user-sops
  namespace: demo
spec:
  secretTemplates:
    - name: demo-mariadb-user
      labels:
        k8s.mariadb.com/watch: "true"
      stringData:
        password: ENC[AES256_GCM,data:PB3l0+8AWchl1sajRtdtssAVRnKtBjrMjj9msOu4eCmPCzjcr69IZKmkAvQDLdFP/w==,iv:k5jqgCUlaMZNn4lQomdnKs0VTibASXviHcOioleGWzw=,tag:57PEe0A/9FNcNTqLfXRHKQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV2YvR3VFeVd6TVNXTFNj
        Wjd5eVBhdDVid2VrSTkwNXFyZ2Q4NzR3WGo0CjBHc1lCM0RtV1U5bUhiMThPZEhU
        VWZxN1RwK1hYZ2lPRWlBdHdYWlFFUEEKLS0tIHFBSTRTZGFGUG5pZ09PaTMyM0sx
        S0dITm9mWDZTeVdNaEY1c3NpZjd0TG8Krq5C44fTeKtJ12IYz5ujkW0nhsnhSZcF
        6aBImHrAWYpXUJNJVqD1azhMvNFyBi2l/kx1vveMmCPKQOMWVyIoXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(stringData|data)$
  lastmodified: "2026-08-18T16:37:47Z"
  mac: ENC[AES256_GCM,data:9Yu8lpE6z5G9GCp1kjSlfs30rhTF11iLSptqdfR58z3lZfQt6DYooxE+xb5lemXTYAV4YMeBv3cQIRpUTL4VWzMhu9XSaBSCID3mE+5Xr9FxioXFNaPVwOpn/0Szp+tGhkRz8MsKg7phoW5f5JXI9iiTQCo6uUjsVxWXiJXnUfU=,iv:Kzie0JTSZYuNKHk6Og4ZsWtndjdkaqlV3t7+cG8gifM=,tag:x3KsmPS62TGriT6oeDroUw==,type:str]
  version: 3.13.3
