---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: demo-k8up-b2-sops
  namespace: demo
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:eyjUbE++nA==,iv:DpCdwV9Mxe+W52RxFIk/X8KEgdbxf5HzD+4Pw5qmLm8=,tag:4rXKU2CXk2+XOMNan3TndA==,type:str]
      stringData:
        repository-password: ENC[AES256_GCM,data:LgJ1pwuXih7rz2u8tI1GjrSQypg95pOZ39J95siLGdyUHhZ1e1x/vuExQz7UTRQdAls=,iv:mIYWI00I6ySp7AHY2oCrMZFdc0WpnBrYP0+BlwsWXVQ=,tag:t3tvGvdOw4M7bkFsetGUUw==,type:str]
        account-id: ENC[AES256_GCM,data:1+NWq02iFG8Rv5GYRQwPv0WTV5mMobxmAQ==,iv:p7871tZI0qAkBQnKPSgYGTh57YkP32Fac+BhupCwAqw=,tag:zCWVQnbmbDA52U6oisa0aA==,type:str]
        account-key: ENC[AES256_GCM,data:kSZsQAx9pj67D1mnpTlfaAky4IEnRPQgX1wex5t56Q==,iv:cFjDjK6JEuOkJ7nXNXheqw/DRRZz5MNoXeRH1QWACJs=,tag:CJ/f3ELSc07KRwml1Uai8A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQkVKVkdUaHJXNHFQbU8y
        UW5KR0t1OHREYWl5QTJZbU9YNCt3WFpnV2pvCnB5V29aL1ovdHFkWW5WY2pOVGla
        ZlBwYy9uT3RNclh2OFNTTHRyU21TcjAKLS0tIFZSR2d2N3ZSY01MSHpiSHQxQXZa
        NkNGbE9CalhnVVdsZjZFNWdWblhsWWMK8wS7uK8tl9kNh3YijSs6rSgdwCeaW0yj
        zw9AInIN1+ra0/45jl7B6xoC+jb1XUSHzJImpgn9VSjgFZSStEvLuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(spec)$
  lastmodified: "2026-06-09T18:28:15Z"
  mac: ENC[AES256_GCM,data:fg1FcC+Dx9apZKjbnQdYL8RrgliiAhmWtulmr3LOZCaqhlNYQEzayvs6Urp9rR5xyGKQ4SGi2npnQikwLiM3XDizfxfG1x+aXKoMMWokuiJPqetkKY1Mf0LqV7VGU/uXob9v4AGhNmortaNrGjDAlPgh9mBPDOGHPOoGJMTMTqc=,iv:KZw823FcSEMlmKdworxb9MVTmtjlhUyGnX4sT6RXhks=,tag:vOCrISxupRqj46bbVLfMTg==,type:str]
  version: 3.13.1
