# Using bogus values for the secret data, this is just a demo to show how to use SopsSecret with K8up.
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: demo-k8up-b2-sops
  namespace: demo
spec:
  secretTemplates:
    - name: k8up-b2
      stringData:
        repository-password: ENC[AES256_GCM,data:hSa/EEUrfQBMKa5GwG82F0h7nKezEaKaARjXc8KV+/P5,iv:PC3rMosfI0AXWlk993sZd/i4TuWKLbtQObZTeeIudRU=,tag:VOvaKcs39glqhHknv+Rl0Q==,type:str]
        account-id: ENC[AES256_GCM,data:tOqz4eDBgeG1zFEJyhvgnTjA2aRBvhaa+ApeTj8qAA==,iv:V/PwVYHR7w77L/hmNjr/iL4iP79iheVlaVh4CLdt8m4=,tag:9YVl/SJkQil66MqK3mb9bw==,type:str]
        account-key: ENC[AES256_GCM,data:lO0JH0QHT7rI8v3eFQ5Rqs/wlowPUVfYsS5hnhwgDuekYTho8ZEOPg==,iv:uU8ArHKI/os0UjTvYYiQtigk6T0E05nex/JizLuaYEY=,tag:XAWpA75hHPGnyc8GVHzm4Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM3ZUcWhYUDZVU1dCdGFK
        WWtUdElHRkZLYVpZa3lrQ3NlbTlhNXdiOHdzClM0am1vRGhuUUFReUVrM05DOE5m
        YXNLQndZS1BjUEwyRGVvMkRQazhodFEKLS0tIHk2N1hZT3RlK2xEcU9RTmxGL0Zo
        UXdwWExpcE00endVY1QvMk5ya3VqVGcKAa+g/xolQjL9cZvTshi/DdKiIjFkeU95
        g7YmXZ7OJrWjYSi5C6SL9tv6HRW/j5AiHjVFerd7RnZvR4seYMyfEw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(stringData|data)$
  lastmodified: "2026-08-18T16:36:12Z"
  mac: ENC[AES256_GCM,data:Ns1I3+5stihlfcrJDIg+r4ixHQ693LCrEuXsYpl5+CMhdIgh3aBUVuPuJUvkEpf5elU6fmETOyJkl38FhbZuU30HYOIFsSsb0YJCtSsR3araqNR8OkfxQKwNyF0nFkb2u+yHS6JcN9ycjqEvmOa4WawMSteM3l3De1fe337UVG8=,iv:I78ShWvOPfsqZvWVLJz7kdzEyBjNx+7YHIil3EqGG4w=,tag:2WUNoBUReAml7RKRQWgckg==,type:str]
  version: 3.13.3
