---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: demo
  namespace: demo
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: argocd
spec:
  mariaDbRef:
    name: mariadb-cluster
    namespace: mariadb
  passwordSecretKeyRef:
    name: demo-mariadb-user
    key: password
