---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-pushgateway
spec:
  interval: 1h
  chart:
    spec:
      chart: prometheus-pushgateway
      version: ^2.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    serviceMonitor:
      enabled: true
      # For some reason the ServiceMonitor has a default namespace of "monitoring".
      # If we set it to a falsy value, it's defaulted to the Charts namespace.
      namespace: ""
