---
apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:WkWPM6rr35zqr601EiFEx33P6TpVMO8UPfhwduORryCK7EOPtgHxMnQDRJzX+QHyiJCK0CLaxkNcRNmdp/xeqdQDML9lD3lDkTObEQq3C5Qi6dNmHYgkUVtUMepxexPCvUfrhBAwZN/k9dJDDEQGLCzd00cxfd/cUlZpALs47q6p5IoevJRDEmGRDOI4EIhNMv0KbxFe+IrWJ3Lbu0CS07rDQypv1JmZ2NFc2b7C1QyEnLlN30+/PNcSYxo6Vi+MkjVbaEX4GYKBlvAVPjts8ugMLLS4RefH,iv:crzh6uactnurH18DOtAQCiKjUA1whv028Li7tomdbkM=,tag:hlPE5OQ7dTgBehSo05AFsQ==,type:str]
kind: Secret
metadata:
  name: wieseschwarm-credentials
sops:
  age:
    - recipient: age17l7vdytw3g9y6780fy0c4ga7a9yhmy4xvhnc4866c0qdr37m9p7qy0a06v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyODljSzlkdHI0WHFrYjJk
        MUZqTlNZVHc5TnhyRXp4ZEdYcGYxdHcrK20wCms0RDNZemlmVXN6SXMyN3FMTWgw
        VW1wbVVZVHRhWnorWGRKbk1IQlpId2sKLS0tIFEra1p3RW9FMGowNU9Gd0Y4ZEhV
        Y3hydGx3MzRTcGRQQ3VvaXJ4d2UvU3MKZNEV6SUGTZXH70E8rgvCNVkw1kOViylM
        D/HHBcgNFo1yOc0Y+gcbXndTeg70C1+D+hfFPtTupAakzk2vsFfv2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-11-19T17:03:12Z"
  mac: ENC[AES256_GCM,data:UXqCn81tBmIJHa7DDrkDxrN/5PXS9sUg33805sZTxgMVka9f7vynPxtOI4a3EJF/Ky8Q+C9Zmqejx8Yq97N8qHuM70idWA5jhVx4joepWDBM0Rg35juAJux2Hy1DaJ5CUaA+sIQXra7sncMajQSwceeFzXbvIW/AaE2pZDY3cws=,iv:XYP+a6jwW2d2IAga2eNjWUoYq1DSNOKGBq5tpE/+Hn4=,tag:EP3A5Z/vIIcnAAXltM4zYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
