---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cloudflared-token-sops
  namespace: cloudflared
spec:
  secretTemplates:
    - name: cloudflared-token
      stringData:
        token: ENC[AES256_GCM,data:atHWoeWO5G+MHw1a4w1KsgefNSvVCkD/5nOTplji2GDn75ZGZT9dj9/IPZ4IgAr5KtmURJ8jGUem1ZbR9WxRM+UHov2sC/Hfr9RbGBf0jX8xVNzNNpYHNzJqpcDXXS+9dAXgc4wcgs9M8MipZTWJg7BwKYTFEyiSVhzVLT1j9pLXvtjOoeh376mJD4n/RF4qWXFNwNZAvQuV8eIIVvUO20rKYMjih2OVTYYwnuGd6CjWxMy2jV4GeA==,iv:S/stFWbQ6WTSAEMUA3go8Ca1DRovvZa4xoZX8rYXk8k=,tag:jCTalZD3Qsr68tUGdqa42g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa09xZVBSbmVjT2VtazJC
        YTJUYUVjRC83ODJvVmpQQVdvREVFWVRkQ0Q4Cklrb3dBOG9KcWhXcHI0ZXJkL25K
        MWFZODFzQTJYRldDZjJRb1ZMQ1Y0R0UKLS0tIGFJb29WNEVEQW1yN3hlSmZENjJS
        YTZRYkRTTjhpelltK1NzaVY0SnpoeWMKsCTRjGUUM6T+64wge2BAFF9DxUFEv3E5
        XUb8FggL7lVRrwiD3hPMs1FcPEtDtBJnatjOsCdFuzrcs349uvu0NQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mnmvtkxyzmcfs973tm0tzypq3rgyqelww3h2w92e4navh8zx3e5q60e8wy
  encrypted_regex: ^(stringData|data)$
  lastmodified: "2026-06-10T09:09:08Z"
  mac: ENC[AES256_GCM,data:73syntnBJ/NOaXtDOG608XiIEOkVZ/6dnzN0YUFtZ0MTxm8CcD2AcNU5B3hX75jr4WNulZHxjdHNsIOVLNQpQaRkbFe4JeO0ynjI58vqbRdaxwmWsr3zcWvV63lGdaOMaPGEWEHNGGdE+qAk90NNUM3lha9X0gwSqP/E8YpWqsw=,iv:z5aYJomVNnzEhb8Lmc50vDrCo8wvIEL3EGrRwpQFFeA=,tag:Kl81HZ14uD4jA0qOV/JdHg==,type:str]
  version: 3.13.1
