---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      # Run default hooks (in case pre-commit wasn't installed on commiters side)
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
      # Run additional longer running pre-commit hooks
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --hook-stage pre-commit --hook-stage pre-push
