---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: composable-system

resources:
  # As Composable currently does not have the manifests and CRDs separated, this was done manually
  - manifests.yaml
  # Roles for Composable to use cert-manager
  - rbac.yaml
