---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-issuer-editor
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["clusterissuers"]
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: letsencrypt-email-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["letsencrypt-email"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: composable-letsencrypt-email-secret-reader
subjects:
  - kind: ServiceAccount
    name: composable-controller-manager
    namespace: composable-system
roleRef:
  kind: Role
  name: letsencrypt-email-secret-reader
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: composable-clusterissuer-editor
subjects:
  - kind: ServiceAccount
    name: composable-controller-manager
    namespace: composable-system
roleRef:
  kind: ClusterRole
  name: cluster-issuer-editor
  apiGroup: rbac.authorization.k8s.io
